# This notebook is an introduction to R


## Data Types in R

### R has 6 basic data types:
    
    character: "a", "swc"
    numeric: 2, 15.5
    integer: 2L (the L tells R to store this as an integer)
    logical: TRUE, FALSE
    complex: 1+4i (complex numbers with real and imaginary parts)

Assign variables with an assignment operator: <- 

In [7]:
name <- "Deana"
age  <- 33L
true <- TRUE

print(name)
print(age)
print(true)
typeof(name)
typeof(age)
typeof(true)


[1] "Deana"
[1] 33
[1] TRUE


[1] "character"

[1] "integer"

[1] "logical"

## Vectors

A vector is the most common and basic data structure in R and is pretty much the workhorse of R. Technically, vectors can be one of two types:

    atomic vectors
    lists
   
   although the term “vector” most commonly refers to the atomic types not to lists.

In [12]:
#an empty 'logical' (default) vector
vector()
print(vector())

logical(0)

logical(0)


In [14]:
#You can create vectors in differt modes by defining them or by calling constructors
vector("character", length = 4) #a vector of 4 emtpy chacters elements

[1] "" "" "" ""

In [15]:
character(4) #the same thing

[1] "" "" "" ""

In [31]:
#lets fill a vector, x,  with different elements
x<- c("hey", "I", "am", "a", "vector")
x

typeof(x)

[1] "hey"    "I"      "am"     "a"      "vector"

[1] "character"

In [32]:
#you can access different elements in a vector with element position like Python lists but R starts at element 1 (not 0 like with Python)

x[1]
x[2:4]

[1] "hey"

[1] "I"  "am" "a"

In [33]:
#add elements like this:
x <- c(x, "today")
x
#if you worded it like this, it would be combined to the end x <- c("today", x)

[1] "hey"    "I"      "am"     "a"      "vector" "today"

In [38]:
#When you put mixed datatypes in a vector, R will create a vector in the mode that works best for all the datatypes. - this is called coercion 
xx <- c(1.7, "a")
xx
xy <- c(FALSE, 2) #False is 0 and True is 1
xy
xz <- c("a", TRUE)
xz

[1] "1.7" "a"

[1] 0 2

[1] "a"    "TRUE"

In [39]:
#you can also control how vectors are coerced. Check out how the character element in xx is turned in a N/A
as.numeric(xx)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"


[1] 1.7  NA

## Matrix

Matrices are an extension of numeric or character vectors with demensions of columns and rows.

In [41]:
#Matrices are filled column wise

m <- matrix(1:6, nrow = 2, ncol = 3)

m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [44]:
dim(m)
class(m)
typeof(m)

[1] 2 3

[1] "matrix" "array"

[1] "integer"

In [47]:
#You can take a vector and transform it into a matrix like this
x <- 1:10
dim(x) <-c(2,5)
print(x)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [48]:
#You can also use cbind and rbind to bind columns into a matrix
r <- 1:3
s <- 14:16
cbind(r,s)

r s 
[1,] 1 14
[2,] 2 15
[3,] 3 16

In [50]:
rbind(r,s)

[,1] [,2] [,3]
r  1    2    3  
s 14   15   16

  [,1] [,2] [,3]
r    1    2    3
s   14   15   16


## Lists
Lists (or generic vectors) act as containers. Unlike atomic vectors, the contents of a list can be different types

In [55]:
x <- list(1, "b", FALSE, 1+4i)
x
length(x)
x[3]

[[1]]
[1] 1

[[2]]
[1] "b"

[[3]]
[1] FALSE

[[4]]
[1] 1+4i

[1] 4

[[1]]
[1] FALSE

In [ ]:
#elements in a list can have names

In [53]:
x <- list(a = 1, b = "b", c = FALSE, d = 1+4i)
names(x)

[1] "a" "b" "c" "d"

## Data Frames

A data frame is a special type of list composed of vectors of equal length.

In [62]:
#You can create your own dataframes
name <- c("Mike", "Lucy", "John") 
age <- c(20, 25, 30) 
student <- c(TRUE, FALSE, TRUE) 
df = data.frame(name, age, student)  
df
df[["age"]]
df$age


name age student
1 Mike 20   TRUE  
2 Lucy 25  FALSE  
3 John 30   TRUE

[1] 20 25 30

[1] 20 25 30

### Useful Data Frame Functions
    head() - shows first 6 rows
    tail() - shows last 6 rows
    dim() - returns the dimensions of data frame (i.e. number of rows and number of columns)
    nrow() - number of rows
    ncol() - number of columns
    str() - structure of data frame - name, type and preview of data in each column
    names() or colnames() - both show the names attribute for a data frame
    sapply(dataframe, class) - shows the class of each column in the data frame

In [66]:
dim(df)
ncol(df)
str(df)

[1] 3 3

[1] 3

'data.frame':	3 obs. of  3 variables:
 $ name   : chr  "Mike" "Lucy" "John"
 $ age    : num  20 25 30
 $ student: logi  TRUE FALSE TRUE


## Reading from and Writing to CSV files

In [67]:
#You can write a dataframe to a csv very easily
write.csv(df, file="sample_df_to_csv_in_R.csv")

In [69]:
#You can create data frames by read.csv() and read.table()
df1 <- read.csv(file="sample_df_to_csv_in_R.csv")

In [70]:
df1

X name age student
1 1 Mike 20   TRUE  
2 2 Lucy 25  FALSE  
3 3 John 30   TRUE

In [82]:
#the header argument is default set to TRUE, set it to FALSE if the first row of your csv file is not your headers. The strip.white argument removes white spaces around the values in csv. It must also include the seperater argument.
df1 <- read.csv(file="sample_df_to_csv_in_R.csv", 
                header=FALSE, 
                strip.white=TRUE, 
                sep=',')
names(df1) = c("index","names","ages","students")
df1

index names ages students
1 NA    name  age  student 
2  1    Mike  20   TRUE    
3  2    Lucy  25   FALSE   
4  3    John  30   TRUE

## Playing with Data Frames
The R dyplr package provides ways to explore your data

In [87]:
install.packages("dplyr")
library("dplyr")


The downloaded binary packages are in
	/var/folders/4v/lbw09b5s3nvbz8d937j_q9pm0000gp/T//RtmpKuj6Em/downloaded_packages



Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union




In [92]:
df <- read.csv(file="christmas_recipes.csv")
dim(df) #shows dimensions

[1] 42  6

In [89]:
head(df) #shows the beginning of the dataset

Title                                           Time Servings     
1 Perfect roast turkey                            180  10 serving(s)
2 Stuffed roast turkey breast                     180  8 serving(s) 
3 Nigella's turkey breast with Christmas stuffing 150  12 serving(s)
4 Gordon Ramsay's roast turkey crown              120  8 serving(s) 
5 Roast turkey crown                              180  8 serving(s) 
6 Roast turkey roll                               150  8 serving(s) 
  Ingredients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
1 ['20ml/\302\276fl oz rapeseed oil', '1 x 5kg/11lb good-quality free-range turkey, preferably organically reared, wishbone removed (ask your butcher to remove the wings and neck and chop them into 2.5cm/1in pieces to use in the dish)', '40g/1\302\275oz unsalted butter, softened to room temperature', '2 pinches sea salt flakes', '2 pinches freshly ground white pepper', '200ml/7fl oz water', 'salt and freshly ground black pepper', '1-2 tsp ground arrowroot (depending on how thick you like your gravy), dissolved in 1 tbsp cold water', 'roast potatoes and steamed seasonal vegetables, to serve']                                                                                                                                                                                                                       
2 ['1 tbsp sunflower oil', '1 onion, finely chopped', '1 leek, trimmed and finely sliced', '4 pork sausages, around 275g/9\302\276oz', '50g/1\302\276oz dried cranberries', '25g/1oz flaked almonds', '1 unwaxed lemon, finely grated zest only', '1 heaped tbsp roughly chopped fresh thyme leaves', '40g/1\302\275oz dried white breadcrumbs', 'salt and freshly ground black pepper', '1.5kg/3lb 5oz turkey breast joint, fully thawed if frozen', '16 rashers smoked streaky bacon', '2 tbsp sunflower oil, plus extra for oiling', 'fresh thyme and bay leaves, to garnish', '2 tbsp plain flour', 'splash of wine', '450ml/16fl oz chicken stock, made with 1 chicken stock cube', '1 tbsp redcurrant jelly']                                                                                                                          
3 ['100g/3\302\275oz dried cranberries', '100ml/3\302\275fl oz Marsala', '2 tbsp olive oil', '2 banana shallots, finely chopped', '\302\274 tsp ground cloves', '\302\275 tsp ground allspice', '2 tsp chopped fresh sage', '1kg/2lb 4oz Italian sausages', '2 free-range eggs, beaten', '50g/2oz parmesan, grated', '60g/2\302\274oz breadcrumbs', '5kg/11lb double breast turkey joint, boned, butterflied, with skin left on', '4 tbsp duck or goose fat']                                                                                                                                                                                                                                                                                                                                                                                
4 ['125g/4\302\275oz pack unsalted butter, softened', '3-4 sprigs fresh thyme, leaves only', 'sprig of fresh rosemary, chopped leaves only', '2 tbsp fresh parsley leaves, chopped', 'salt', 'freshly ground black pepper', '2.2kg/4lb 14oz medium-sized turkey crown',

In [94]:
#filter() selects rows based on values
serves_8 <- df %>% filter(Servings == "10 serving(s)", Time >= 120)
dim(serves_8)

[1] 3 6

In [101]:
#select() selects columns by variables
turkey <- df %>% filter( Title =="Stuffed roast turkey breast")
shopping_list <- turkey %>% select(Ingredients)
shopping_list

Ingredients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
1 ['1 tbsp sunflower oil', '1 onion, finely chopped', '1 leek, trimmed and finely sliced', '4 pork sausages, around 275g/9\302\276oz', '50g/1\302\276oz dried cranberries', '25g/1oz flaked almonds', '1 unwaxed lemon, finely grated zest only', '1 heaped tbsp roughly chopped fresh thyme leaves', '40g/1\302\275oz dried white breadcrumbs', 'salt and freshly ground black pepper', '1.5kg/3lb 5oz turkey breast joint, fully thawed if frozen', '16 rashers smoked streaky bacon', '2 tbsp sunflower oil, plus extra for oiling', 'fresh thyme and bay leaves, to garnish', '2 tbsp plain flour', 'splash of wine', '450ml/16fl oz chicken stock, made with 1 chicken stock cube', '1 tbsp redcurrant jelly']

In [105]:
#arrange() lets you arrange by a column
serves_8 %>% arrange(Time)

Title                       Time Servings     
1 Honey-glazed gammon         150  10 serving(s)
2 Slow cooker honey roast ham 150  10 serving(s)
3 Perfect roast turkey        180  10 serving(s)
  Ingredients                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
1 ['2kg/4lb 8oz unsmoked boneless gammon joint, tied', '2 onions, halved', '2 carrots, unpeeled, cut into 5cm/2in pieces', '2 celery stalks, cut into 5cm/2in pieces', '4 bay leaves', '12 black peppercorns', 'small handful cloves', '4 tbsp runny honey', '4 tbsp English mustard']                                                                                                                                                                                                                                                                                                                                
2 ['1.6kg/3lb 8oz boneless, rolled smoked or unsmoked gammon', '1 onion, peeled and quartered', '1 tbsp English mustard', '1 tbsp clear honey', '2 tbsp demerara sugar']                                                                                                                                                                                                                                                                                                                                                                                                                                              
3 ['20ml/\302\276fl oz rapeseed oil', '1 x 5kg/11lb good-quality free-range turkey, preferably organically reared, wishbone removed (ask your butcher to remove the wings and neck and chop them into 2.5cm/1in pieces to use in the dish)', '40g/1\302\275oz unsalted butter, softened to room temperature', '2 pinches sea salt flakes', '2 pinches freshly ground white pepper', '200ml/7fl oz water', 'salt and freshly ground black pepper', '1-2 tsp ground arrowroot (depending on how thick you like your gravy), dissolved in 1 tbsp cold water', 'roast potatoes and steamed seasonal vegetables, to serve']
  Instructions                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [104]:
#summerize takes a summary from multiple values in your Data Frame
df %>%
summarize(averge_time = mean(Time))


averge_time
1 92.85714

These are just a few ways to explore data with R. Check it out and learn more for yourself! https://www.r-project.org/

Sources for this research include:

John Blischak, Daniel Chen, Harriet Dashnow, and Denis Haine (eds):
"Software Carpentry: Programming with R."  Version 2016.06, June 2016,
https://github.com/swcarpentry/r-novice-inflammation,
10.5281/zenodo.57541.

Codeacademy.com

6 Most Useful dplyr Commands to Manipulate a Data Frame in R, cmdline, January 27, 2018 https://cmdlinetips.com/2018/01/6-most-useful-dplyr-verbs-to-manipulate-a-data-frame-in-r/